package form;

import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author glaucomunsberg
 */
public class Chess extends javax.swing.JFrame {

    /**
     * Creates new form Chess
     */
    public Chess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        //bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel12 = new javax.swing.JPanel();
        j1A = new javax.swing.JPanel();
        j1B = new javax.swing.JPanel();
        j1C = new javax.swing.JPanel();
        j1D = new javax.swing.JPanel();
        j1E = new javax.swing.JPanel();
        j1F = new javax.swing.JPanel();
        j1G = new javax.swing.JPanel();
        j1H = new javax.swing.JPanel();
        j2A = new javax.swing.JPanel();
        j3A = new javax.swing.JPanel();
        j4A = new javax.swing.JPanel();
        j5A = new javax.swing.JPanel();
        j6A = new javax.swing.JPanel();
        j7A = new javax.swing.JPanel();
        j8C = new javax.swing.JPanel();
        j2B = new javax.swing.JPanel();
        j2C = new javax.swing.JPanel();
        j2D = new javax.swing.JPanel();
        j2E = new javax.swing.JPanel();
        j2F = new javax.swing.JPanel();
        j2G = new javax.swing.JPanel();
        j2H = new javax.swing.JPanel();
        j3B = new javax.swing.JPanel();
        j3C = new javax.swing.JPanel();
        j3D = new javax.swing.JPanel();
        j3E = new javax.swing.JPanel();
        j3F = new javax.swing.JPanel();
        j3G = new javax.swing.JPanel();
        j3H = new javax.swing.JPanel();
        j4B = new javax.swing.JPanel();
        j4C = new javax.swing.JPanel();
        j4D = new javax.swing.JPanel();
        j4E = new javax.swing.JPanel();
        j4F = new javax.swing.JPanel();
        j4G = new javax.swing.JPanel();
        j4H = new javax.swing.JPanel();
        j5B = new javax.swing.JPanel();
        j5C = new javax.swing.JPanel();
        j5D = new javax.swing.JPanel();
        j5E = new javax.swing.JPanel();
        j6H = new javax.swing.JPanel();
        j5F = new javax.swing.JPanel();
        j5G = new javax.swing.JPanel();
        j5H = new javax.swing.JPanel();
        j6G = new javax.swing.JPanel();
        j6F = new javax.swing.JPanel();
        j6E = new javax.swing.JPanel();
        j6D = new javax.swing.JPanel();
        j6C = new javax.swing.JPanel();
        j6B = new javax.swing.JPanel();
        j7B = new javax.swing.JPanel();
        j7C = new javax.swing.JPanel();
        j7D = new javax.swing.JPanel();
        j7E = new javax.swing.JPanel();
        j7F = new javax.swing.JPanel();
        j7G = new javax.swing.JPanel();
        j7H = new javax.swing.JPanel();
        j8A = new javax.swing.JPanel();
        j8B = new javax.swing.JPanel();
        j8D = new javax.swing.JPanel();
        j8E = new javax.swing.JPanel();
        j8F = new javax.swing.JPanel();
        j8G = new javax.swing.JPanel();
        j8H = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMaximumSize(null);
        setMinimumSize(null);

        //org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ObjectProperty.create(), this, org.jdesktop.beansbinding.BeanProperty.create("iconImage"));
        //bindingGroup.addBinding(binding);

        j1A.setBackground(new java.awt.Color(153, 153, 153));
        j1A.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j1ALayout = new javax.swing.GroupLayout(j1A);
        j1A.setLayout(j1ALayout);
        j1ALayout.setHorizontalGroup(
            j1ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j1ALayout.setVerticalGroup(
            j1ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j1B.setBackground(new java.awt.Color(204, 204, 204));
        j1B.setMaximumSize(new java.awt.Dimension(80, 80));
        j1B.setMinimumSize(new java.awt.Dimension(80, 80));
        j1B.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j1BLayout = new javax.swing.GroupLayout(j1B);
        j1B.setLayout(j1BLayout);
        j1BLayout.setHorizontalGroup(
            j1BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j1BLayout.setVerticalGroup(
            j1BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j1C.setBackground(new java.awt.Color(153, 153, 153));
        j1C.setMaximumSize(new java.awt.Dimension(80, 80));
        j1C.setMinimumSize(new java.awt.Dimension(80, 80));
        j1C.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j1CLayout = new javax.swing.GroupLayout(j1C);
        j1C.setLayout(j1CLayout);
        j1CLayout.setHorizontalGroup(
            j1CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j1CLayout.setVerticalGroup(
            j1CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j1D.setBackground(new java.awt.Color(204, 204, 204));
        j1D.setMaximumSize(new java.awt.Dimension(80, 80));
        j1D.setMinimumSize(new java.awt.Dimension(80, 80));
        j1D.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j1DLayout = new javax.swing.GroupLayout(j1D);
        j1D.setLayout(j1DLayout);
        j1DLayout.setHorizontalGroup(
            j1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j1DLayout.setVerticalGroup(
            j1DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j1E.setBackground(new java.awt.Color(153, 153, 153));
        j1E.setMaximumSize(new java.awt.Dimension(80, 80));
        j1E.setMinimumSize(new java.awt.Dimension(80, 80));
        j1E.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j1ELayout = new javax.swing.GroupLayout(j1E);
        j1E.setLayout(j1ELayout);
        j1ELayout.setHorizontalGroup(
            j1ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j1ELayout.setVerticalGroup(
            j1ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j1F.setBackground(new java.awt.Color(204, 204, 204));
        j1F.setMaximumSize(new java.awt.Dimension(80, 80));
        j1F.setMinimumSize(new java.awt.Dimension(80, 80));
        j1F.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j1FLayout = new javax.swing.GroupLayout(j1F);
        j1F.setLayout(j1FLayout);
        j1FLayout.setHorizontalGroup(
            j1FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j1FLayout.setVerticalGroup(
            j1FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j1G.setBackground(new java.awt.Color(153, 153, 153));
        j1G.setMaximumSize(new java.awt.Dimension(80, 80));
        j1G.setMinimumSize(new java.awt.Dimension(80, 80));
        j1G.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j1GLayout = new javax.swing.GroupLayout(j1G);
        j1G.setLayout(j1GLayout);
        j1GLayout.setHorizontalGroup(
            j1GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j1GLayout.setVerticalGroup(
            j1GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j1H.setBackground(new java.awt.Color(204, 204, 204));
        j1H.setMaximumSize(new java.awt.Dimension(80, 80));
        j1H.setMinimumSize(new java.awt.Dimension(80, 80));
        j1H.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j1HLayout = new javax.swing.GroupLayout(j1H);
        j1H.setLayout(j1HLayout);
        j1HLayout.setHorizontalGroup(
            j1HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j1HLayout.setVerticalGroup(
            j1HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j2A.setBackground(new java.awt.Color(204, 204, 204));
        j2A.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j2ALayout = new javax.swing.GroupLayout(j2A);
        j2A.setLayout(j2ALayout);
        j2ALayout.setHorizontalGroup(
            j2ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j2ALayout.setVerticalGroup(
            j2ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j3A.setBackground(new java.awt.Color(153, 153, 153));
        j3A.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j3ALayout = new javax.swing.GroupLayout(j3A);
        j3A.setLayout(j3ALayout);
        j3ALayout.setHorizontalGroup(
            j3ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j3ALayout.setVerticalGroup(
            j3ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j4A.setBackground(new java.awt.Color(204, 204, 204));
        j4A.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j4ALayout = new javax.swing.GroupLayout(j4A);
        j4A.setLayout(j4ALayout);
        j4ALayout.setHorizontalGroup(
            j4ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j4ALayout.setVerticalGroup(
            j4ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j5A.setBackground(new java.awt.Color(153, 153, 153));
        j5A.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j5ALayout = new javax.swing.GroupLayout(j5A);
        j5A.setLayout(j5ALayout);
        j5ALayout.setHorizontalGroup(
            j5ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j5ALayout.setVerticalGroup(
            j5ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j6A.setBackground(new java.awt.Color(204, 204, 204));
        j6A.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j6ALayout = new javax.swing.GroupLayout(j6A);
        j6A.setLayout(j6ALayout);
        j6ALayout.setHorizontalGroup(
            j6ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j6ALayout.setVerticalGroup(
            j6ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j7A.setBackground(new java.awt.Color(153, 153, 153));
        j7A.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j7ALayout = new javax.swing.GroupLayout(j7A);
        j7A.setLayout(j7ALayout);
        j7ALayout.setHorizontalGroup(
            j7ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j7ALayout.setVerticalGroup(
            j7ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j8C.setBackground(new java.awt.Color(204, 204, 204));
        j8C.setMaximumSize(new java.awt.Dimension(80, 80));
        j8C.setMinimumSize(new java.awt.Dimension(80, 80));
        j8C.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j8CLayout = new javax.swing.GroupLayout(j8C);
        j8C.setLayout(j8CLayout);
        j8CLayout.setHorizontalGroup(
            j8CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j8CLayout.setVerticalGroup(
            j8CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j2B.setBackground(new java.awt.Color(153, 153, 153));
        j2B.setMaximumSize(new java.awt.Dimension(80, 80));
        j2B.setMinimumSize(new java.awt.Dimension(80, 80));
        j2B.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j2BLayout = new javax.swing.GroupLayout(j2B);
        j2B.setLayout(j2BLayout);
        j2BLayout.setHorizontalGroup(
            j2BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j2BLayout.setVerticalGroup(
            j2BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j2C.setBackground(new java.awt.Color(204, 204, 204));
        j2C.setMaximumSize(new java.awt.Dimension(80, 80));
        j2C.setMinimumSize(new java.awt.Dimension(80, 80));
        j2C.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j2CLayout = new javax.swing.GroupLayout(j2C);
        j2C.setLayout(j2CLayout);
        j2CLayout.setHorizontalGroup(
            j2CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j2CLayout.setVerticalGroup(
            j2CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j2D.setBackground(new java.awt.Color(153, 153, 153));
        j2D.setMaximumSize(new java.awt.Dimension(80, 80));
        j2D.setMinimumSize(new java.awt.Dimension(80, 80));
        j2D.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j2DLayout = new javax.swing.GroupLayout(j2D);
        j2D.setLayout(j2DLayout);
        j2DLayout.setHorizontalGroup(
            j2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j2DLayout.setVerticalGroup(
            j2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j2E.setBackground(new java.awt.Color(204, 204, 204));
        j2E.setMaximumSize(new java.awt.Dimension(80, 80));
        j2E.setMinimumSize(new java.awt.Dimension(80, 80));
        j2E.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j2ELayout = new javax.swing.GroupLayout(j2E);
        j2E.setLayout(j2ELayout);
        j2ELayout.setHorizontalGroup(
            j2ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j2ELayout.setVerticalGroup(
            j2ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j2F.setBackground(new java.awt.Color(153, 153, 153));
        j2F.setMaximumSize(new java.awt.Dimension(80, 80));
        j2F.setMinimumSize(new java.awt.Dimension(80, 80));
        j2F.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j2FLayout = new javax.swing.GroupLayout(j2F);
        j2F.setLayout(j2FLayout);
        j2FLayout.setHorizontalGroup(
            j2FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j2FLayout.setVerticalGroup(
            j2FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j2G.setBackground(new java.awt.Color(204, 204, 204));
        j2G.setMaximumSize(new java.awt.Dimension(80, 80));
        j2G.setMinimumSize(new java.awt.Dimension(80, 80));
        j2G.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j2GLayout = new javax.swing.GroupLayout(j2G);
        j2G.setLayout(j2GLayout);
        j2GLayout.setHorizontalGroup(
            j2GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j2GLayout.setVerticalGroup(
            j2GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j2H.setBackground(new java.awt.Color(153, 153, 153));
        j2H.setMaximumSize(new java.awt.Dimension(80, 80));
        j2H.setMinimumSize(new java.awt.Dimension(80, 80));
        j2H.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j2HLayout = new javax.swing.GroupLayout(j2H);
        j2H.setLayout(j2HLayout);
        j2HLayout.setHorizontalGroup(
            j2HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j2HLayout.setVerticalGroup(
            j2HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j3B.setBackground(new java.awt.Color(204, 204, 204));
        j3B.setMaximumSize(new java.awt.Dimension(80, 80));
        j3B.setMinimumSize(new java.awt.Dimension(80, 80));
        j3B.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j3BLayout = new javax.swing.GroupLayout(j3B);
        j3B.setLayout(j3BLayout);
        j3BLayout.setHorizontalGroup(
            j3BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j3BLayout.setVerticalGroup(
            j3BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j3C.setBackground(new java.awt.Color(153, 153, 153));
        j3C.setMaximumSize(new java.awt.Dimension(80, 80));
        j3C.setMinimumSize(new java.awt.Dimension(80, 80));
        j3C.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j3CLayout = new javax.swing.GroupLayout(j3C);
        j3C.setLayout(j3CLayout);
        j3CLayout.setHorizontalGroup(
            j3CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j3CLayout.setVerticalGroup(
            j3CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j3D.setBackground(new java.awt.Color(204, 204, 204));
        j3D.setMaximumSize(new java.awt.Dimension(80, 80));
        j3D.setMinimumSize(new java.awt.Dimension(80, 80));
        j3D.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j3DLayout = new javax.swing.GroupLayout(j3D);
        j3D.setLayout(j3DLayout);
        j3DLayout.setHorizontalGroup(
            j3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j3DLayout.setVerticalGroup(
            j3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j3E.setBackground(new java.awt.Color(153, 153, 153));
        j3E.setMaximumSize(new java.awt.Dimension(80, 80));
        j3E.setMinimumSize(new java.awt.Dimension(80, 80));
        j3E.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j3ELayout = new javax.swing.GroupLayout(j3E);
        j3E.setLayout(j3ELayout);
        j3ELayout.setHorizontalGroup(
            j3ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j3ELayout.setVerticalGroup(
            j3ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j3F.setBackground(new java.awt.Color(204, 204, 204));
        j3F.setMaximumSize(new java.awt.Dimension(80, 80));
        j3F.setMinimumSize(new java.awt.Dimension(80, 80));
        j3F.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j3FLayout = new javax.swing.GroupLayout(j3F);
        j3F.setLayout(j3FLayout);
        j3FLayout.setHorizontalGroup(
            j3FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j3FLayout.setVerticalGroup(
            j3FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j3G.setBackground(new java.awt.Color(153, 153, 153));
        j3G.setMaximumSize(new java.awt.Dimension(80, 80));
        j3G.setMinimumSize(new java.awt.Dimension(80, 80));
        j3G.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j3GLayout = new javax.swing.GroupLayout(j3G);
        j3G.setLayout(j3GLayout);
        j3GLayout.setHorizontalGroup(
            j3GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j3GLayout.setVerticalGroup(
            j3GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j3H.setBackground(new java.awt.Color(204, 204, 204));
        j3H.setMaximumSize(new java.awt.Dimension(80, 80));
        j3H.setMinimumSize(new java.awt.Dimension(80, 80));
        j3H.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j3HLayout = new javax.swing.GroupLayout(j3H);
        j3H.setLayout(j3HLayout);
        j3HLayout.setHorizontalGroup(
            j3HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j3HLayout.setVerticalGroup(
            j3HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j4B.setBackground(new java.awt.Color(153, 153, 153));
        j4B.setMaximumSize(new java.awt.Dimension(80, 80));
        j4B.setMinimumSize(new java.awt.Dimension(80, 80));
        j4B.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j4BLayout = new javax.swing.GroupLayout(j4B);
        j4B.setLayout(j4BLayout);
        j4BLayout.setHorizontalGroup(
            j4BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j4BLayout.setVerticalGroup(
            j4BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j4C.setBackground(new java.awt.Color(204, 204, 204));
        j4C.setMaximumSize(new java.awt.Dimension(80, 80));
        j4C.setMinimumSize(new java.awt.Dimension(80, 80));
        j4C.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j4CLayout = new javax.swing.GroupLayout(j4C);
        j4C.setLayout(j4CLayout);
        j4CLayout.setHorizontalGroup(
            j4CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j4CLayout.setVerticalGroup(
            j4CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j4D.setBackground(new java.awt.Color(153, 153, 153));
        j4D.setMaximumSize(new java.awt.Dimension(80, 80));
        j4D.setMinimumSize(new java.awt.Dimension(80, 80));
        j4D.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j4DLayout = new javax.swing.GroupLayout(j4D);
        j4D.setLayout(j4DLayout);
        j4DLayout.setHorizontalGroup(
            j4DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j4DLayout.setVerticalGroup(
            j4DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j4E.setBackground(new java.awt.Color(204, 204, 204));
        j4E.setMaximumSize(new java.awt.Dimension(80, 80));
        j4E.setMinimumSize(new java.awt.Dimension(80, 80));
        j4E.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j4ELayout = new javax.swing.GroupLayout(j4E);
        j4E.setLayout(j4ELayout);
        j4ELayout.setHorizontalGroup(
            j4ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j4ELayout.setVerticalGroup(
            j4ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j4F.setBackground(new java.awt.Color(153, 153, 153));
        j4F.setMaximumSize(new java.awt.Dimension(80, 80));
        j4F.setMinimumSize(new java.awt.Dimension(80, 80));
        j4F.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j4FLayout = new javax.swing.GroupLayout(j4F);
        j4F.setLayout(j4FLayout);
        j4FLayout.setHorizontalGroup(
            j4FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j4FLayout.setVerticalGroup(
            j4FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j4G.setBackground(new java.awt.Color(204, 204, 204));
        j4G.setMaximumSize(new java.awt.Dimension(80, 80));
        j4G.setMinimumSize(new java.awt.Dimension(80, 80));
        j4G.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j4GLayout = new javax.swing.GroupLayout(j4G);
        j4G.setLayout(j4GLayout);
        j4GLayout.setHorizontalGroup(
            j4GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j4GLayout.setVerticalGroup(
            j4GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j4H.setBackground(new java.awt.Color(153, 153, 153));
        j4H.setMaximumSize(new java.awt.Dimension(80, 80));
        j4H.setMinimumSize(new java.awt.Dimension(80, 80));
        j4H.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j4HLayout = new javax.swing.GroupLayout(j4H);
        j4H.setLayout(j4HLayout);
        j4HLayout.setHorizontalGroup(
            j4HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j4HLayout.setVerticalGroup(
            j4HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j5B.setBackground(new java.awt.Color(204, 204, 204));
        j5B.setMaximumSize(new java.awt.Dimension(80, 80));
        j5B.setMinimumSize(new java.awt.Dimension(80, 80));
        j5B.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j5BLayout = new javax.swing.GroupLayout(j5B);
        j5B.setLayout(j5BLayout);
        j5BLayout.setHorizontalGroup(
            j5BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j5BLayout.setVerticalGroup(
            j5BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j5C.setBackground(new java.awt.Color(153, 153, 153));
        j5C.setMaximumSize(new java.awt.Dimension(80, 80));
        j5C.setMinimumSize(new java.awt.Dimension(80, 80));
        j5C.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j5CLayout = new javax.swing.GroupLayout(j5C);
        j5C.setLayout(j5CLayout);
        j5CLayout.setHorizontalGroup(
            j5CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j5CLayout.setVerticalGroup(
            j5CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j5D.setBackground(new java.awt.Color(204, 204, 204));
        j5D.setMaximumSize(new java.awt.Dimension(80, 80));
        j5D.setMinimumSize(new java.awt.Dimension(80, 80));
        j5D.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j5DLayout = new javax.swing.GroupLayout(j5D);
        j5D.setLayout(j5DLayout);
        j5DLayout.setHorizontalGroup(
            j5DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j5DLayout.setVerticalGroup(
            j5DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j5E.setBackground(new java.awt.Color(153, 153, 153));
        j5E.setMaximumSize(new java.awt.Dimension(80, 80));
        j5E.setMinimumSize(new java.awt.Dimension(80, 80));
        j5E.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j5ELayout = new javax.swing.GroupLayout(j5E);
        j5E.setLayout(j5ELayout);
        j5ELayout.setHorizontalGroup(
            j5ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j5ELayout.setVerticalGroup(
            j5ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j6H.setBackground(new java.awt.Color(153, 153, 153));
        j6H.setMaximumSize(new java.awt.Dimension(80, 80));
        j6H.setMinimumSize(new java.awt.Dimension(80, 80));
        j6H.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j6HLayout = new javax.swing.GroupLayout(j6H);
        j6H.setLayout(j6HLayout);
        j6HLayout.setHorizontalGroup(
            j6HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j6HLayout.setVerticalGroup(
            j6HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j5F.setBackground(new java.awt.Color(204, 204, 204));
        j5F.setMaximumSize(new java.awt.Dimension(80, 80));
        j5F.setMinimumSize(new java.awt.Dimension(80, 80));
        j5F.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j5FLayout = new javax.swing.GroupLayout(j5F);
        j5F.setLayout(j5FLayout);
        j5FLayout.setHorizontalGroup(
            j5FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j5FLayout.setVerticalGroup(
            j5FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j5G.setBackground(new java.awt.Color(153, 153, 153));
        j5G.setMaximumSize(new java.awt.Dimension(80, 80));
        j5G.setMinimumSize(new java.awt.Dimension(80, 80));
        j5G.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j5GLayout = new javax.swing.GroupLayout(j5G);
        j5G.setLayout(j5GLayout);
        j5GLayout.setHorizontalGroup(
            j5GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j5GLayout.setVerticalGroup(
            j5GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j5H.setBackground(new java.awt.Color(204, 204, 204));
        j5H.setMaximumSize(new java.awt.Dimension(80, 80));
        j5H.setMinimumSize(new java.awt.Dimension(80, 80));
        j5H.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j5HLayout = new javax.swing.GroupLayout(j5H);
        j5H.setLayout(j5HLayout);
        j5HLayout.setHorizontalGroup(
            j5HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j5HLayout.setVerticalGroup(
            j5HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j6G.setBackground(new java.awt.Color(204, 204, 204));
        j6G.setMaximumSize(new java.awt.Dimension(80, 80));
        j6G.setMinimumSize(new java.awt.Dimension(80, 80));
        j6G.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j6GLayout = new javax.swing.GroupLayout(j6G);
        j6G.setLayout(j6GLayout);
        j6GLayout.setHorizontalGroup(
            j6GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j6GLayout.setVerticalGroup(
            j6GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j6F.setBackground(new java.awt.Color(153, 153, 153));
        j6F.setMaximumSize(new java.awt.Dimension(80, 80));
        j6F.setMinimumSize(new java.awt.Dimension(80, 80));
        j6F.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j6FLayout = new javax.swing.GroupLayout(j6F);
        j6F.setLayout(j6FLayout);
        j6FLayout.setHorizontalGroup(
            j6FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j6FLayout.setVerticalGroup(
            j6FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j6E.setBackground(new java.awt.Color(204, 204, 204));
        j6E.setMaximumSize(new java.awt.Dimension(80, 80));
        j6E.setMinimumSize(new java.awt.Dimension(80, 80));
        j6E.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j6ELayout = new javax.swing.GroupLayout(j6E);
        j6E.setLayout(j6ELayout);
        j6ELayout.setHorizontalGroup(
            j6ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j6ELayout.setVerticalGroup(
            j6ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j6D.setBackground(new java.awt.Color(153, 153, 153));
        j6D.setMaximumSize(new java.awt.Dimension(80, 80));
        j6D.setMinimumSize(new java.awt.Dimension(80, 80));
        j6D.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j6DLayout = new javax.swing.GroupLayout(j6D);
        j6D.setLayout(j6DLayout);
        j6DLayout.setHorizontalGroup(
            j6DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j6DLayout.setVerticalGroup(
            j6DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j6C.setBackground(new java.awt.Color(204, 204, 204));
        j6C.setMaximumSize(new java.awt.Dimension(80, 80));
        j6C.setMinimumSize(new java.awt.Dimension(80, 80));
        j6C.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j6CLayout = new javax.swing.GroupLayout(j6C);
        j6C.setLayout(j6CLayout);
        j6CLayout.setHorizontalGroup(
            j6CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j6CLayout.setVerticalGroup(
            j6CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j6B.setBackground(new java.awt.Color(153, 153, 153));
        j6B.setMaximumSize(new java.awt.Dimension(80, 80));
        j6B.setMinimumSize(new java.awt.Dimension(80, 80));
        j6B.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j6BLayout = new javax.swing.GroupLayout(j6B);
        j6B.setLayout(j6BLayout);
        j6BLayout.setHorizontalGroup(
            j6BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j6BLayout.setVerticalGroup(
            j6BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j7B.setBackground(new java.awt.Color(204, 204, 204));
        j7B.setMaximumSize(new java.awt.Dimension(80, 80));
        j7B.setMinimumSize(new java.awt.Dimension(80, 80));
        j7B.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j7BLayout = new javax.swing.GroupLayout(j7B);
        j7B.setLayout(j7BLayout);
        j7BLayout.setHorizontalGroup(
            j7BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j7BLayout.setVerticalGroup(
            j7BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j7C.setBackground(new java.awt.Color(153, 153, 153));
        j7C.setMaximumSize(new java.awt.Dimension(80, 80));
        j7C.setMinimumSize(new java.awt.Dimension(80, 80));
        j7C.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j7CLayout = new javax.swing.GroupLayout(j7C);
        j7C.setLayout(j7CLayout);
        j7CLayout.setHorizontalGroup(
            j7CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j7CLayout.setVerticalGroup(
            j7CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j7D.setBackground(new java.awt.Color(204, 204, 204));
        j7D.setMaximumSize(new java.awt.Dimension(80, 80));
        j7D.setMinimumSize(new java.awt.Dimension(80, 80));
        j7D.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j7DLayout = new javax.swing.GroupLayout(j7D);
        j7D.setLayout(j7DLayout);
        j7DLayout.setHorizontalGroup(
            j7DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j7DLayout.setVerticalGroup(
            j7DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j7E.setBackground(new java.awt.Color(153, 153, 153));
        j7E.setMaximumSize(new java.awt.Dimension(80, 80));
        j7E.setMinimumSize(new java.awt.Dimension(80, 80));
        j7E.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j7ELayout = new javax.swing.GroupLayout(j7E);
        j7E.setLayout(j7ELayout);
        j7ELayout.setHorizontalGroup(
            j7ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j7ELayout.setVerticalGroup(
            j7ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j7F.setBackground(new java.awt.Color(204, 204, 204));
        j7F.setMaximumSize(new java.awt.Dimension(80, 80));
        j7F.setMinimumSize(new java.awt.Dimension(80, 80));
        j7F.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j7FLayout = new javax.swing.GroupLayout(j7F);
        j7F.setLayout(j7FLayout);
        j7FLayout.setHorizontalGroup(
            j7FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j7FLayout.setVerticalGroup(
            j7FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j7G.setBackground(new java.awt.Color(153, 153, 153));
        j7G.setMaximumSize(new java.awt.Dimension(80, 80));
        j7G.setMinimumSize(new java.awt.Dimension(80, 80));
        j7G.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j7GLayout = new javax.swing.GroupLayout(j7G);
        j7G.setLayout(j7GLayout);
        j7GLayout.setHorizontalGroup(
            j7GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j7GLayout.setVerticalGroup(
            j7GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j7H.setBackground(new java.awt.Color(204, 204, 204));
        j7H.setMaximumSize(new java.awt.Dimension(80, 80));
        j7H.setMinimumSize(new java.awt.Dimension(80, 80));
        j7H.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j7HLayout = new javax.swing.GroupLayout(j7H);
        j7H.setLayout(j7HLayout);
        j7HLayout.setHorizontalGroup(
            j7HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j7HLayout.setVerticalGroup(
            j7HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j8A.setBackground(new java.awt.Color(204, 204, 204));
        j8A.setMaximumSize(new java.awt.Dimension(80, 80));
        j8A.setMinimumSize(new java.awt.Dimension(80, 80));
        j8A.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j8ALayout = new javax.swing.GroupLayout(j8A);
        j8A.setLayout(j8ALayout);
        j8ALayout.setHorizontalGroup(
            j8ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j8ALayout.setVerticalGroup(
            j8ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j8B.setBackground(new java.awt.Color(153, 153, 153));
        j8B.setMaximumSize(new java.awt.Dimension(80, 80));
        j8B.setMinimumSize(new java.awt.Dimension(80, 80));
        j8B.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j8BLayout = new javax.swing.GroupLayout(j8B);
        j8B.setLayout(j8BLayout);
        j8BLayout.setHorizontalGroup(
            j8BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j8BLayout.setVerticalGroup(
            j8BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j8D.setBackground(new java.awt.Color(153, 153, 153));
        j8D.setMaximumSize(new java.awt.Dimension(80, 80));
        j8D.setMinimumSize(new java.awt.Dimension(80, 80));
        j8D.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j8DLayout = new javax.swing.GroupLayout(j8D);
        j8D.setLayout(j8DLayout);
        j8DLayout.setHorizontalGroup(
            j8DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j8DLayout.setVerticalGroup(
            j8DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j8E.setBackground(new java.awt.Color(204, 204, 204));
        j8E.setMaximumSize(new java.awt.Dimension(80, 80));
        j8E.setMinimumSize(new java.awt.Dimension(80, 80));
        j8E.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j8ELayout = new javax.swing.GroupLayout(j8E);
        j8E.setLayout(j8ELayout);
        j8ELayout.setHorizontalGroup(
            j8ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j8ELayout.setVerticalGroup(
            j8ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j8F.setBackground(new java.awt.Color(153, 153, 153));
        j8F.setMaximumSize(new java.awt.Dimension(80, 80));
        j8F.setMinimumSize(new java.awt.Dimension(80, 80));
        j8F.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j8FLayout = new javax.swing.GroupLayout(j8F);
        j8F.setLayout(j8FLayout);
        j8FLayout.setHorizontalGroup(
            j8FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j8FLayout.setVerticalGroup(
            j8FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j8G.setBackground(new java.awt.Color(204, 204, 204));
        j8G.setMaximumSize(new java.awt.Dimension(80, 80));
        j8G.setMinimumSize(new java.awt.Dimension(80, 80));
        j8G.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j8GLayout = new javax.swing.GroupLayout(j8G);
        j8G.setLayout(j8GLayout);
        j8GLayout.setHorizontalGroup(
            j8GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j8GLayout.setVerticalGroup(
            j8GLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        j8H.setBackground(new java.awt.Color(153, 153, 153));
        j8H.setMaximumSize(new java.awt.Dimension(80, 80));
        j8H.setMinimumSize(new java.awt.Dimension(80, 80));
        j8H.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout j8HLayout = new javax.swing.GroupLayout(j8H);
        j8H.setLayout(j8HLayout);
        j8HLayout.setHorizontalGroup(
            j8HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        j8HLayout.setVerticalGroup(
            j8HLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A*", "Têmpera simulada", "Subida de encosta" }));

        jLabel1.setText("Algoritmo");

        jButton1.setText("Começar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j8A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j3A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j4A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(j5A, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(j6A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j7A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j1B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j1C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j1F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j1G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j1H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(j2B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j2C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j2E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j2F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j2G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j2H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(j3B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j3C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j3E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j3F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j3G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j3H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(j4B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j4C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j4D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j4E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j4F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j4G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(j4H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j5B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j5C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j5D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j5E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j5F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j5G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j5H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(j6B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j6C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j6D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j6E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j6F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j6G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j6H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(j7B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j7C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j7D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j7E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j7F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j7G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j7H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(j8B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j8C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j8D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j8E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j8F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j8G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j8H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j1A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j3A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j4A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j5A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j6A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j7A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j8A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j2B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j3B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j4B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j5B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j6H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j6G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j6F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j6E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j6D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j6C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j6B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j7B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j7C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j7D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j7E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j7F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j7G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j7H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j8C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j8B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j8D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j8E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j8F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j8G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j8H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel j1A;
    private javax.swing.JPanel j1B;
    private javax.swing.JPanel j1C;
    private javax.swing.JPanel j1D;
    private javax.swing.JPanel j1E;
    private javax.swing.JPanel j1F;
    private javax.swing.JPanel j1G;
    private javax.swing.JPanel j1H;
    private javax.swing.JPanel j2A;
    private javax.swing.JPanel j2B;
    private javax.swing.JPanel j2C;
    private javax.swing.JPanel j2D;
    private javax.swing.JPanel j2E;
    private javax.swing.JPanel j2F;
    private javax.swing.JPanel j2G;
    private javax.swing.JPanel j2H;
    private javax.swing.JPanel j3A;
    private javax.swing.JPanel j3B;
    private javax.swing.JPanel j3C;
    private javax.swing.JPanel j3D;
    private javax.swing.JPanel j3E;
    private javax.swing.JPanel j3F;
    private javax.swing.JPanel j3G;
    private javax.swing.JPanel j3H;
    private javax.swing.JPanel j4A;
    private javax.swing.JPanel j4B;
    private javax.swing.JPanel j4C;
    private javax.swing.JPanel j4D;
    private javax.swing.JPanel j4E;
    private javax.swing.JPanel j4F;
    private javax.swing.JPanel j4G;
    private javax.swing.JPanel j4H;
    private javax.swing.JPanel j5A;
    private javax.swing.JPanel j5B;
    private javax.swing.JPanel j5C;
    private javax.swing.JPanel j5D;
    private javax.swing.JPanel j5E;
    private javax.swing.JPanel j5F;
    private javax.swing.JPanel j5G;
    private javax.swing.JPanel j5H;
    private javax.swing.JPanel j6A;
    private javax.swing.JPanel j6B;
    private javax.swing.JPanel j6C;
    private javax.swing.JPanel j6D;
    private javax.swing.JPanel j6E;
    private javax.swing.JPanel j6F;
    private javax.swing.JPanel j6G;
    private javax.swing.JPanel j6H;
    private javax.swing.JPanel j7A;
    private javax.swing.JPanel j7B;
    private javax.swing.JPanel j7C;
    private javax.swing.JPanel j7D;
    private javax.swing.JPanel j7E;
    private javax.swing.JPanel j7F;
    private javax.swing.JPanel j7G;
    private javax.swing.JPanel j7H;
    private javax.swing.JPanel j8A;
    private javax.swing.JPanel j8B;
    private javax.swing.JPanel j8C;
    private javax.swing.JPanel j8D;
    private javax.swing.JPanel j8E;
    private javax.swing.JPanel j8F;
    private javax.swing.JPanel j8G;
    private javax.swing.JPanel j8H;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel12;
    //private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
